[build]
  base = "frontend"
  publish = "out"
  command = "npm install && npm run build && npm run export"

[build.environment]
  NODE_VERSION = "20.0.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions = "functions"
  force = true

[build.environment]
  NODE_VERSION = "14"
