'use client';

import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Dictionnaire des traductions
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Nos Services',
    'nav.contact': 'Contact',
    'nav.locations': 'Nos Implantations',
    'nav.faq': 'FAQ',
    'nav.testimonials': 'Témoignages',
    'nav.contact_us': 'Nous Contacter',
    'common.contact_us': 'Nous Contacter',
    
    // Footer
    'footer.slogan': "Let's travel and build a better world together",
    'footer.contact_us': 'Nous contacter',
    'footer.services': 'Nos Services',
    'footer.cargo': 'Cargo aérien et maritime',
    'footer.currency': 'Change de devises',
    'footer.consulting': 'Conseils et assistance',
    'footer.visa': 'Services de visa',
    'footer.business': 'Création d\'entreprise',
    'footer.it': 'Solutions IT',
    'footer.locations': 'Nos Implantations',
    'footer.quick_links': 'Liens Rapides',
    'footer.choose_language': 'Choisir la langue',
    'footer.copyright': 'Tous droits réservés',
    'footer.rights': 'Tous droits réservés',
    'footer.contact_email': 'paulworld2016@yahoo.com',
    'footer.our_services': 'Nos Services',
    'services.cargo_shipping': 'Services d\'expédition de marchandises',
    'services.air_freight': 'Expédition aérienne',
    'services.ocean_freight': 'Expédition maritime',
    'services.customs_clearance': 'Dédouanement',
    'services.logistics_solutions': 'Solutions logistiques',
    'contact.contact_us': 'Contactez-nous',
    'footer.all_rights_reserved': 'Tous droits réservés',
    'footer.privacy_policy': 'Politique de confidentialité',
    'footer.terms_of_service': 'Conditions d\'utilisation',
    'footer.cookies': 'Gestion des cookies',
    'services.cargoservices.business_title': 'Services d\'expédition',
    'services.it_title': 'Solutions IT',
    'services.customs_title': 'Services de dédouanement',
    'services.cargo_title': 'Services d\'Expédition',
    
    // Home Page
    'home.welcome': 'Bienvenue chez Paul World Travel',
    'home.subtitle': 'Votre partenaire de confiance pour vos affaires internationales',
    'home.slogan': "Let's travel and build a better world together",
    'home.services.title': 'Nos Services',
    'home.services.subtitle': 'Découvrez notre gamme complète de services pour vous accompagner dans vos projets internationaux',
    'home.services.description': 'Des solutions adaptées à tous vos besoins internationaux, du transport de marchandises aux services administratifs.',
    'home.services.view_all': 'Voir tous nos services',
    'home.services.learn_more': 'En savoir plus',
    'home.carousel.paused': 'Pause',
    'home.carousel.auto': 'Auto',
    'home.cta_button': 'En savoir plus',
    'home.contact_button': 'Nous contacter',
    'home.cta.title': 'Prêt à démarrer votre projet ?',
    'home.cta.subtitle': 'Contactez-nous dès aujourd\'hui pour discuter de vos besoins et découvrir comment nous pouvons vous aider',
    
    // Home - Services Carousel
    'services.cargo_china_africa_title': 'Cargo aérien et maritime Chine-Afrique',
    'services.cargo_china_africa_desc': 'Transport de marchandises entre la Chine et l\'Afrique',
    'services.cargo_china_usa_title': 'Cargo aérien et maritime Chine-Canada & USA',
    'services.cargo_china_usa_desc': 'Transport de marchandises entre la Chine et l\'Amérique du Nord',
    'services.currency_title': 'Change de Devises',
    // Services section with unique keys only
    'services.currency_desc': 'Conversion entre Yuan, FCFA et Dollars',
    'services.china_consulting_title': 'Conseils et assistance pour les achats en Chine',
    'services.china_consulting_desc': 'Accompagnement pour vos achats et négociations en Chine',
    'services.travel_title': 'Voyage-tourisme-Formation',
    'services.travel_desc': 'Organisation de voyages, formation et tourisme',
    'services.free_consultation': 'Consultation gratuite',
    'services.need_custom_service': 'Besoin d\'un service personnalisé ?',
    'services.custom_service_desc': 'Nous offrons des solutions sur mesure pour répondre à vos besoins spécifiques.',
    'services.sea_transport': 'Transport maritime',
    'services.sea_transport_desc': 'Transport maritime de vos marchandises avec suivi en temps réel',
    'services.air_transport': 'Transport aérien',
    'services.air_transport_desc': 'Livraison rapide de vos marchandises par avion',
    'services.door_to_door': 'Service porte à porte',
    'services.door_to_door_desc': 'Transport complet depuis l\'usine jusqu\'à votre entrepôt ou point de vente.',
    'services.real_time_tracking': 'Suivi en Temps Réel',
    'services.real_time_tracking_desc': 'Accès à notre plateforme de suivi pour connaître la position exacte de vos marchandises.',
    'services.why_choose_cargo': 'Pourquoi choisir nos services de fret ?',
    'services.why_choose_cargo_desc': 'Des années d\'expérience, des partenaires fiables et un service client exceptionnel.',
    'services.currency_exchange': 'Change de devises',
    'services.currency_exchange_desc': 'Conversion de Yuan, FCFA et Dollars à des taux compétitifs',
    'services.china_purchasing': 'Achats en Chine',
    'services.china_purchasing_desc': 'Assistance pour vos achats et négociations en Chine',
    'services.travel_services': 'Services de voyage',
    'services.travel_services_desc': 'Organisation de voyages d\'affaires et de tourisme',
    'services.training_programs': 'Programmes de formation',
    'services.training_programs_desc': 'Formation professionnelle sur mesure pour vos besoins',
    'services.student_visa': 'Visa Étudiant',
    'services.student_visa_desc': 'Accompagnement pour l\'obtention de votre visa étudiant',
    'services.student_visa_support': 'Support de candidature',
    'services.student_visa_counseling': 'Conseil personnalisé',
    'services.student_visa_interview': 'Préparation à l\'entretien',
    'services.student_visa_follow_up': 'Suivi de dossier',
    'services.business_visa': 'Visa d\'affaires',
    'services.business_visa_desc': 'Accompagnement pour l\'obtention de votre visa d\'affaires',
    // Visa and immigration services
    'services.work_visa': 'Visa de travail',
    'services.work_visa_desc': 'Accompagnement pour l\'obtention de votre visa de travail',
    'services.family_reunification': 'Regroupement familial',
    'services.family_reunification_desc': 'Accompagnement pour vos démarches de regroupement familial',
    'services.refugee_status': 'Statut de réfugié',
    'services.refugee_status_desc': 'Accompagnement pour l\'obtention du statut de réfugié',
    
    // Business and travel services
    'services.business_travel': 'Voyages d\'affaires',
    'services.business_travel_desc': 'Voyages organisés et programmes de formation personnalisés',
    'services.travel_services': 'Services de voyage',
    'services.travel_services_desc': 'Organisation de voyages d\'affaires et de tourisme',
    'services.plan_trip': 'Planifier un voyage',
    
    // Training and translation services
    'services.translation_title': 'Services de Traduction',
    'services.translation_desc': 'Traduction professionnelle de documents officiels',
    'services.training_title': 'Formation Professionnelle',
    'services.training_desc': 'Programmes de formation adaptés à vos besoins',
    'services.training_programs': 'Programmes de formation',
    'services.training_programs_desc': 'Formation professionnelle sur mesure pour vos besoins',
    'services.tourism_title': 'Services Touristiques',
    'services.tourism_desc': 'Organisation de voyages et séjours touristiques sur mesure',
    
    // Cargo and logistics services
    'services.air_transport': 'Transport aérien',
    'services.air_transport_desc': 'Livraison rapide de vos marchandises par avion',
    'services.door_to_door': 'Service porte à porte',
    'services.door_to_door_desc': 'Transport complet depuis l\'usine jusqu\'à votre entrepôt ou point de vente.',
    'services.real_time_tracking': 'Suivi en Temps Réel',
    'services.real_time_tracking_desc': 'Accès à notre plateforme de suivi pour connaître la position exacte de vos marchandises.',
    'services.why_choose_cargo': 'Pourquoi choisir nos services de fret ?',
    'services.why_choose_cargo_desc': 'Des années d\'expérience, des partenaires fiables et un service client exceptionnel.',
    
    // Business and financial services
    'services.currency_exchange': 'Change de devises',
    'services.currency_exchange_desc': 'Conversion de Yuan, FCFA et Dollars à des taux compétitifs',
    'services.china_purchasing': 'Achats en Chine',
    'services.china_purchasing_desc': 'Assistance pour vos achats et négociations en Chine',
    
    // General services
    'services.free_consultation': 'Consultation gratuite',
    'services.need_custom_service': 'Besoin d\'un service personnalisé ?',
    'services.custom_service_desc': 'Nous offrons des solutions sur mesure pour répondre à vos besoins spécifiques.',
    
    // Home - Cameroon Section
    'home.cameroon.proud': 'Notre siège principal au Cameroun',
    'home.cameroon.quality_services': 'Depuis notre siège à Douala, nous vous proposons des services de qualité pour tous vos projets internationaux',
    'home.cameroon.title': 'Notre siège principal au Cameroun',
    'home.cameroon.description': 'Depuis notre siège à Douala, nous vous proposons des services de qualité pour tous vos projets internationaux',
    'home.cameroon.office_title': 'Notre siège principal',
    'home.cameroon.douala_lendi': 'Douala, Lendi',
    'home.cameroon.office_description': 'Notre bureau principal est situé à Douala, centre économique du Cameroun. C\'est de là que nous coordonnons toutes nos opérations.',
    'home.cameroon.learn_more': 'En savoir plus sur notre siège au Cameroun',
    'home.cameroon.contact_team': 'Contactez notre équipe au Cameroun',
    'home.locations.douala': 'Douala, Cameroun',
    'home.locations.hq': 'Notre siège principal',
    
    // Home - China Section
    'home.china.services_title': 'Nos Services en Chine',
    'home.china.services_subtitle': 'Depuis notre bureau à Foshan, nous vous accompagnons dans tous vos projets en Chine',
    'home.china.foshan': 'Foshan, Guangdong',
    'home.china.operations_center': 'Notre centre d\'opérations en Chine',
    'home.china.expertise_title': 'Services et expertise en Chine',
    'home.china.expertise_description': 'Notre présence en Chine nous permet de vous offrir un accompagnement complet pour tous vos projets commerciaux et personnels.',
    'home.china.services.sourcing': 'Sourcing et Achats',
    'home.china.services.sourcing_desc': 'Assistance pour trouver les meilleurs fournisseurs et négocier les prix',
    'home.china.services.currency': 'Change de Devises',
    'home.china.services.currency_desc': 'Conversion entre Yuan, FCFA et Dollars à des taux compétitifs',
    'home.china.services.quality': 'Contrôle Qualité',
    'home.china.services.quality_desc': 'Inspection des produits avant expédition pour garantir leur qualité',
    'home.china.services.admin': 'Assistance Administrative',
    'home.china.services.admin_desc': 'Aide pour les visas, l\'immigration et les démarches administratives',
    'home.china.discover_all': 'Découvrir tous nos services en Chine',
    
    // About Page - Désactivé
    /*
    'about.title': 'À propos de nous',
    'about.subtitle': 'Votre partenaire pour les affaires internationales',
    'about.history_title': 'Notre histoire',
    'about.history_p1': 'Paul World Travel a été fondée avec pour mission de faciliter les échanges commerciaux et culturels entre l\'Afrique, la Chine et l\'Amérique du Nord. Notre siège social est situé à Douala, au Cameroun, avec une présence stratégique à Foshan, en Chine.',
    'about.history_p2': 'Au fil des années, nous avons construit un réseau solide de partenaires et de clients, nous permettant d\'offrir des solutions sur mesure pour le fret aérien et maritime, l\'échange de devises, et l\'assistance aux achats en Chine.',
    'about.history_p3': 'Notre équipe multiculturelle est dédiée à fournir des services de qualité, en s\'appuyant sur une expertise locale et une vision globale des affaires internationales.',
    'about.mission_values_title': 'Mission, Valeurs & Vision',
    'about.mission_title': 'Notre mission',
    'about.mission_desc': 'Faciliter les échanges commerciaux et culturels entre les continents, en offrant des services logistiques et de consulting fiables et efficaces.',
    'about.values_title': 'Nos valeurs',
    'about.values_desc': 'Intégrité, transparence, et engagement envers la satisfaction de nos clients.',
    'about.vision_title': 'Notre vision',
    'about.vision_desc': 'Devenir le partenaire de référence pour les entreprises cherchant à s\'implanter ou à commercer entre l\'Afrique, la Chine et l\'Amérique du Nord.',
    */
    
    // Services Page
    'services.title': 'Nos Services',
    'services.subtitle': 'Des solutions complètes pour vos besoins d\'affaires',
    'services.all': 'Tous les services',
    'services.cargo_china_africa_title': 'Fret Aérien et Maritime Chine-Afrique',
    'services.cargo_china_africa_desc': 'Transport sécurisé de marchandises entre la Chine et l\'Afrique',
    'services.cargo_china_usa_title': 'Fret Aérien et Maritime Chine-Canada & USA',
    'services.cargo_china_usa_desc': 'Transport sécurisé de marchandises entre la Chine et l\'Amérique du Nord',
    'services.currency_title': 'Change de Devises',
    'services.currency_desc': 'Échange de Yuan, FCFA et Dollars à des taux compétitifs',
    'services.consulting_title': 'Conseil et Assistance pour Achats',
    'services.consulting_desc': 'Expertise pour vos achats en Chine et négociations avec les fournisseurs',
    'services.tourism_title': 'Tourisme et Formation',
    'services.tourism_desc': 'Voyages organisés et programmes de formation personnalisés',
    'services.visa_title': 'Services de Visa et Immigration',
    'services.visa_desc': 'Assistance complète pour les processus de visa et d\'immigration',
    'services.business_title': 'Création d\'Entreprise',
    'services.business_desc': 'Soutien pour établir et gérer votre entreprise',
    'services.it_title': 'Solutions IT',
    'services.it_desc': 'Services technologiques adaptés aux besoins de votre entreprise',
    'services.customs_title': 'Douanes et Transit',
    'services.customs_desc': 'Gestion efficace des procédures douanières et de transit',
    'services.sea_transport': 'Transport Maritime',
    'services.sea_transport_desc': 'Transport de marchandises par voie maritime avec suivi en temps réel et documentation complète.',
    'services.air_transport': 'Transport Aérien',
    'services.air_transport_desc': 'Livraison rapide par fret aérien pour vos marchandises urgentes ou de grande valeur.',
    'services.door_to_door': 'Services Porte-à-Porte',
    'services.door_to_door_desc': 'Transport complet depuis l\'usine jusqu\'à votre entrepôt ou point de vente.',
    'services.real_time_tracking': 'Suivi en Temps Réel',
    'services.real_time_tracking_desc': 'Accès à notre plateforme de suivi pour suivre la position exacte de vos marchandises.',
    'services.why_choose_cargo': 'Pourquoi choisir nos services de fret ?',
    'services.reliability': 'Fiabilité garantie',
    'services.reliability_desc': 'Plus de 95% de nos livraisons arrivent dans les délais prévus',
    'services.competitive_rates': 'Tarifs compétitifs',
    'services.competitive_rates_desc': 'Prix optimisés grâce à nos partenariats avec les grandes compagnies',
    'services.personalized_service': 'Service personnalisé',
    'services.personalized_service_desc': 'Chaque client bénéficie d\'un conseiller dédié pour suivre ses expéditions',
    'services.global_network': 'Réseau mondial',
    'services.global_network_desc': 'Des partenaires dans plus de 50 pays pour une couverture optimale',
    'services.request_quote': 'Demander un devis',
    'services.global_solutions': 'Des solutions globales adaptées à vos besoins internationaux',
    'services.global_presence': 'Avec des bureaux au Cameroun et en Chine, Paul World Travel vous offre une gamme complète de services pour faciliter vos projets commerciaux et personnels entre l\'Afrique, l\'Asie et l\'Amérique du Nord.',
    'services.estimate_price': 'Estimer un prix',
    'services.business_travel': 'Voyages d\'affaires',
    'services.business_travel_desc': 'Voyages organisés et programmes de formation personnalisés',
    'services.translation_title': 'Services de Traduction',
    'services.translation_desc': 'Traduction professionnelle de documents officiels',
    'services.training_title': 'Formation Professionnelle',
    'services.training_desc': 'Programmes de formation adaptés à vos besoins',
    'services.plan_trip': 'Planifier un voyage',
    'services.need_custom_service': 'Besoin d\'un service personnalisé ?',
    'services.custom_service_desc': 'Nous offrons des solutions sur mesure pour répondre à vos besoins spécifiques.',
    'services.visa_subtitle': 'Assistance pour les démarches de visa et d\'immigration',
    'services.student_visa': 'Visa Étudiant',
    'services.student_visa_desc': 'Assistance pour l\'obtention de votre visa étudiant',
    'services.student_visa_support': 'Support de candidature',
    'services.student_visa_counseling': 'Conseil personnalisé',
    'services.student_visa_interview': 'Préparation à l\'entretien',
    'services.student_visa_follow_up': 'Suivi de dossier',
    'services.permanent_residence': 'Résidence Permanente',
    'services.permanent_residence_desc': 'Assistance pour l\'obtention de votre résidence permanente',
    'services.permanent_residence_support': 'Support de candidature',
    'services.permanent_residence_eligibility': 'Évaluation d\'éligibilité',
    'services.permanent_residence_preparation': 'Préparation du dossier',
    'services.permanent_residence_follow_up': 'Suivi de dossier',
    'services.other_immigration_services': 'Autres services d\'immigration',
    'services.business_visa': 'Visa d\'affaires',
    'services.business_visa_desc': 'Accompagnement pour l\'obtention de votre visa d\'affaires',
    'services.work_visa': 'Visa de travail',
    'services.work_visa_desc': 'Accompagnement pour l\'obtention de votre visa de travail',
    'services.family_reunification': 'Regroupement familial',
    'services.family_reunification_desc': 'Accompagnement pour vos démarches de regroupement familial',
    'services.refugee_status': 'Statut de réfugié',
    'services.refugee_status_desc': 'Accompagnement pour l\'obtention du statut de réfugié',
    'services.free_consultation': 'Consultation gratuite',
    
    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes à votre disposition pour répondre à toutes vos questions',
    'contact.send_message': 'Envoyez-nous un message',
    'contact.send_button': 'Envoyer le message',
    'contact.first_name': 'Prénom',
    'contact.last_name': 'Nom',
    'contact.email': 'Email',
    'contact.subject': 'Sujet',
    'contact.select_subject': 'Sélectionnez un sujet',
    'contact.cargo_services': 'Services de cargo',
    'contact.currency_exchange': 'Change de devises',
    'contact.consulting': 'Conseils et assistance',
    'contact.visa': 'Services de visa',
    'contact.business': 'Création d\'entreprise',
    'contact.it': 'Solutions informatiques',
    'contact.customs': 'Douane et transit',
    'contact.other': 'Autre',
    'contact.message': 'Message',
    'contact.sending': 'Envoi en cours...',
    'contact.send': 'Envoyer le message',
    'contact.success': 'Votre message a été envoyé avec succès. Nous vous contacterons bientôt.',
    'contact.error': 'Une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer.',
    'contact.our_coordinates': 'Nos coordonnées',
    'contact.china_office': 'Bureau en Chine',
    'contact.china_address': 'Foshan, Guangdong, Chine',
    'contact.contact_for_info': 'Contactez-nous pour plus d\'informations',
    'contact.cameroon_office': 'Bureau au Cameroun',
    'contact.cameroon_address': 'Douala, Lendi Entrée Commisssaire',
    'contact.business_hours': 'Heures d\'ouverture',
    'contact.monday_friday': 'Lundi - Vendredi: 8h00 - 17h00',
    'contact.saturday': 'Samedi: 9h00 - 13h00',
    'contact.sunday': 'Dimanche: Fermé',
    'contact.email_address': 'paulworld2016@yahoo.com',
    'contact.form_name': 'Nom',
    'contact.form_phone': 'Téléphone',
    'contact.form_subject': 'Sujet',
    'contact.form_message': 'Message',
    'contact.form_submit': 'Envoyer',
    'contact.address': 'Adresse',
    'contact.phone': 'Téléphone',
    'contact.office_hours': 'Heures d\'ouverture',
    

    
    // FAQ Page
    'faq.title': 'FAQ',
    'faq.category_business': 'Services d\'entreprise',
    'faq.category_it': 'Solutions IT',
    'faq.category_customs': 'Services douaniers',
    'faq.subtitle': 'Réponses à vos questions sur Paul World Travel',
    'faq.search_placeholder': 'Rechercher une question...',
    'faq.category_all': 'Toutes les questions',
    'faq.category_cargo': 'Cargo Aérien et Maritime',
    'faq.category_currency': 'Change de Devises',
    'faq.category_visa': 'Visas et Immigration',
    'faq.category_consulting': 'Conseils et Achats',
    'faq.no_questions': 'Aucune question trouvée dans cette catégorie.',
    'faq.more_questions': 'Vous avez d\'autres questions ?',
    'faq.contact_description': 'Notre équipe est disponible pour répondre à toutes vos questions spécifiques et vous fournir les informations dont vous avez besoin.',
    
    // Locations Page
    'locations.title': 'Nos Implantations',
    'locations.subtitle': 'Présents en Chine et au Cameroun pour vous servir',
    'locations.china_office': 'Notre Bureau en Chine',
    'locations.china_office_alt': 'Bureau en Chine',
    'locations.china_description': 'Notre bureau principal est situé à Foshan, dans la province du Guangdong en Chine, une région stratégique qui est l\'un des centres manufacturiers les plus importants du pays. Cette localisation nous permet de travailler directement avec de nombreux fournisseurs et fabricants pour vous offrir les meilleurs services et produits.',
    'locations.china_address': 'Foshan, Guangdong, Chine',
    'locations.contact_for_info': 'Contactez-nous pour plus d\'informations',
    'locations.cameroon_office': 'Notre Bureau au Cameroun',
    'locations.cameroon_office_alt': 'Bureau au Cameroun',
    'locations.cameroon_description': 'Notre bureau au Cameroun est situé à Douala, la capitale économique du pays. Cette présence en Afrique nous permet de faciliter les échanges commerciaux entre la Chine et l\'Afrique, et d\'offrir un service de proximité à nos clients africains. Notre équipe locale vous accompagne dans tous vos projets avec expertise et professionnalisme.',
    'locations.cameroon_address': 'Douala, Lendi Entrée Commisssaire, Cameroun',
    'locations.global_presence': 'Notre Présence Internationale',
    'locations.global_description': 'Paul World Travel est stratégiquement positionné pour faciliter les échanges entre l\'Asie, l\'Afrique et l\'Amérique du Nord. Notre présence en Chine et au Cameroun nous permet d\'offrir un service personnalisé et efficace à nos clients internationaux.',
    'locations.map_alt': 'Carte mondiale montrant nos implantations',
    'locations.address': 'Adresse',
    'locations.douala_address': 'Douala, Lendi Entrée Commisssaire',
    'locations.phone': 'Téléphone',
    'locations.email': 'Email',
    'locations.hours': 'Heures d\'ouverture',
    
    // Testimonials
    'testimonials.title': 'Témoignages Clients',
    'testimonials.subtitle': 'Ce que nos clients disent de nous',
    'testimonials.add_button': 'Ajouter un témoignage',
    'testimonials.form_name': 'Votre Nom',
    'testimonials.form_company': 'Entreprise (optionnel)',
    'testimonials.form_rating': 'Note',
    'testimonials.form_message': 'Votre témoignage',
    'testimonials.form_submit': 'Soumettre',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Succès !',
    'common.read_more': 'Lire plus',
    'common.learn_more': 'En savoir plus',
    'common.submit': 'Soumettre',
    'common.cancel': 'Annuler',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Our Services',
    'nav.contact': 'Contact',
    'nav.locations': 'Our Locations',
    'nav.faq': 'FAQ',
    'nav.testimonials': 'Testimonials',
    'nav.contact_us': 'Contact Us',
    'common.contact_us': 'Contact Us',
    
    // Footer
    'footer.slogan': "Let's travel and build a better world together",
    'footer.contact_us': 'Contact us',
    'footer.services': 'Our Services',
    'footer.cargo': 'Air and sea cargo',
    'footer.currency': 'Currency exchange',
    'footer.consulting': 'Consulting and assistance',
    'footer.visa': 'Visa services',
    'footer.business': 'Business creation',
    'footer.it': 'IT Solutions',
    'footer.locations': 'Our Locations',
    'footer.quick_links': 'Quick Links',
    'footer.choose_language': 'Choose language',
    'footer.copyright': 'All rights reserved',
    'footer.rights': 'All rights reserved',
    'footer.contact_email': 'paulworld2016@yahoo.com',
    
    // Home Page
    'home.welcome': 'Welcome to Paul World Travel',
    'home.subtitle': 'Your trusted partner for international business',
    'home.slogan': "Let's travel and build a better world together",
    'home.services.title': 'Our Services',
    'home.services.subtitle': 'Discover our complete range of services to support your international projects',
    'home.services.description': 'Tailored solutions for all your international needs, from cargo shipping to administrative services.',
    'home.services.view_all': 'View all our services',
    'home.services.learn_more': 'Learn more',
    'home.carousel.paused': 'Paused',
    'home.carousel.auto': 'Auto',
    'home.cta_button': 'Learn More',
    'home.contact_button': 'Contact Us',
    'home.cta.title': 'Ready to start your project?',
    'home.cta.subtitle': 'Contact us today to discuss your needs and discover how we can help you',
    'footer.our_services': 'Our Services',
    'services.cargo_shipping': 'Cargo Shipping',
    'services.air_freight': 'Air Freight',
    'services.ocean_freight': 'Ocean Freight',
    'services.customs_clearance': 'Customs Clearance',
    'services.logistics_solutions': 'Logistics Solutions',
    'contact.contact_us': 'Contact Us',
    'footer.all_rights_reserved': 'All rights reserved',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.terms_of_service': 'Terms of Service',
    'footer.cookies': 'Cookies',
    'services.cargoservices.business_title': 'Cargo Services',
    'services.it_title': 'IT Solutions',
    'services.customs_title': 'Customs Clearance Services',
    'services.cargo_title': 'Cargo Services',
    
    // Home - Services Carousel
    'services.cargo_china_africa_title': 'Air & Sea Freight China-Africa',
    'services.cargo_china_africa_desc': 'Cargo transportation between China and Africa',
    'services.cargo_china_usa_title': 'Air & Sea Freight China-Canada & USA',
    'services.cargo_china_usa_desc': 'Cargo transportation between China and North America',
    'services.currency_title': 'Currency Exchange',
    'services.currency_desc': 'Currency conversion between Yuan, FCFA, and Dollars',
    'services.china_consulting_title': 'Consulting and Assistance for Purchases in China',
    'services.china_consulting_desc': 'Support for your purchases and negotiations in China',
    'services.travel_title': 'Travel-Tourism-Training',
    'services.travel_desc': 'Travel organization, training, and tourism',
    'services.free_consultation': 'Free Consultation',
    'services.need_custom_service': 'Need a Custom Service?',
    'services.custom_service_desc': 'We offer tailored solutions to meet your specific needs.',
    'services.sea_transport': 'Sea Transport',
    'services.sea_transport_desc': 'Marine transportation of your goods with real-time tracking',
    'services.air_transport': 'Air Transport',
    'services.air_transport_desc': 'Fast delivery of your goods by air',
    'services.door_to_door': 'Door-to-Door Service',
    'services.door_to_door_desc': 'Complete transportation from factory to your warehouse or point of sale',
    'services.real_time_tracking': 'Real-Time Tracking',
    'services.real_time_tracking_desc': 'Access to our tracking platform to know the exact position of your goods',
    'services.why_choose_cargo': 'Why choose our freight services?',
    'services.why_choose_cargo_desc': 'Years of experience, reliable partners, and exceptional customer service',
    'services.reliability': 'Guaranteed Reliability',
    'services.reliability_desc': 'Reliable partners and constant tracking of your goods',
    'services.tracking': 'Real-Time Tracking',
    'services.tracking_desc': '24/7 access to the exact position of your goods',
    'services.customer_service': 'Exceptional Customer Service',
    'services.customer_service_desc': 'Dedicated team to meet your needs',
    'services.experience': 'International Experience',
    'services.experience_desc': 'Years of experience in international freight',
    'services.global_network': 'Global Network',
    'services.global_network_desc': 'Reliable partners worldwide',
    'services.logistics_expertise': 'Logistics Expertise',
    'services.logistics_expertise_desc': 'Team of experts to optimize your deliveries',
    'services.quality_control': 'Quality Control',
    'services.quality_control_desc': 'Inspection of your goods before shipment',
    'services.custom_solutions': 'Custom Solutions',
    'services.custom_solutions_desc': 'Solutions tailored to your specific needs',
    'services.why_choose_us': 'Why Choose Us?',
    'services.why_choose_us_desc': 'Years of experience, reliable partners, and exceptional customer service',
    'services.family_reunification': 'Family Reunification',
    'services.family_reunification_desc': 'Assistance with your family reunification procedures',
    'services.refugee_status': 'Refugee Status',
    'services.refugee_status_desc': 'Assistance for obtaining refugee status',
    'services.business_travel': 'Business Travel',
    'services.business_travel_desc': 'Organized travels and customized training programs',
    'services.translation_title': 'Translation Services',
    'services.translation_desc': 'Professional translation of official documents',
    'services.training_title': 'Professional Training',
    'services.training_desc': 'Training programs adapted to your needs',
    'services.plan_trip': 'Plan a Trip',
    'services.air_transport': 'Air Transport',
    'services.air_transport_desc': 'Fast delivery of your goods by air',
    'services.door_to_door': 'Door-to-Door Service',
    'services.door_to_door_desc': 'Complete transportation from factory to your warehouse or point of sale',
    'services.real_time_tracking': 'Real-Time Tracking',
    'services.real_time_tracking_desc': 'Access to our tracking platform to know the exact position of your goods',
    'services.why_choose_cargo': 'Why choose our freight services?',
    'services.why_choose_cargo_desc': 'Years of experience, reliable partners, and exceptional customer service',
    'services.currency_exchange': 'Currency Exchange',
    'services.currency_exchange_desc': 'Conversion of Yuan, FCFA, and Dollars at competitive rates',
    'services.china_purchasing': 'Purchasing in China',
    'services.china_purchasing_desc': 'Support for your purchases and negotiations in China',
    'services.travel_services': 'Travel Services',
    'services.travel_services_desc': 'Business travel and tourism organization',
    'services.training_programs': 'Training Programs',
    'services.training_programs_desc': 'Customized professional training for your needs',
    'services.tourism_title': 'Tourism Services',
    'services.tourism_desc': 'Organization of tailor-made trips and tourist stays',
    'services.free_consultation': 'Free Consultation',
    'services.need_custom_service': 'Need a Custom Service?',
    'services.custom_service_desc': 'We offer tailored solutions to meet your specific needs.',
    'services.student_visa': 'Student Visa',
    'services.student_visa_desc': 'Comprehensive support for student visa applications.',
    'services.student_visa_support': 'Application Support',
    'services.student_visa_counseling': 'Counseling and Guidance',
    'services.student_visa_interview': 'Interview Preparation',
    'services.student_visa_follow_up': 'Follow-up Services',
    'services.permanent_residence': 'Permanent Residence',
    'services.permanent_residence_desc': 'Assistance with permanent residence applications.',
    'services.permanent_residence_support': 'Application Support',
    'services.permanent_residence_eligibility': 'Eligibility Assessment',
    'services.permanent_residence_preparation': 'Document Preparation',
    'services.permanent_residence_follow_up': 'Follow-up Services',
    'services.other_immigration_services': 'Other Immigration Services',
    'services.business_visa': 'Business Visa',
    'services.business_visa_desc': 'Support for business visa applications and renewals.',
    'services.work_visa': 'Work Visa',
    'services.work_visa_desc': 'Comprehensive assistance for work visa applications.',
    'services.family_reunification': 'Family Reunification',
    'services.family_reunification_desc': 'Guidance on family reunification processes.',
    'services.refugee_status': 'Refugee Status',
    'services.refugee_status_desc': 'Assistance with refugee status applications and support.',
    'services.business_travel': 'Business Travel',
    'services.business_travel_desc': 'Organized travel and customized training programs',
    'services.translation_title': 'Translation Services',
    'services.translation_desc': 'Professional translation of official documents',
    'services.training_title': 'Professional Training',
    'services.training_desc': 'Training programs adapted to your needs',
    'services.plan_trip': 'Plan a Trip',
    'services.need_custom_service': 'Need a Custom Service?',
    'services.custom_service_desc': 'We offer tailored solutions to meet your specific needs.',
    'services.student_visa': 'Student Visa',
    'services.student_visa_desc': 'Assistance with obtaining your student visa',
    'services.student_visa_support': 'Application Support',
    'services.student_visa_counseling': 'Personalized Counseling',
    'services.student_visa_interview': 'Interview Preparation',
    'services.student_visa_follow_up': 'File Follow-up',
    
    // Home - Cameroon Section
    'home.cameroon.title': 'Our main office in Cameroon',
    'home.cameroon.description': 'From our headquarters in Douala, we offer quality services for all your international projects',
    'home.cameroon.office_title': 'Our main headquarters',
    'home.cameroon.douala_lendi': 'Douala, Lendi',
    'home.cameroon.office_description': 'Our main office is located in Douala, the economic center of Cameroon. It is from here that we coordinate all our operations.',
    'home.cameroon.learn_more': 'Learn more about our headquarters in Cameroon',
    'home.cameroon.contact_team': 'Contact our team in Cameroon',
    'home.locations.douala': 'Douala, Cameroon',
    'home.locations.hq': 'Our main headquarters',
    
    // Home - China Section
    'home.china.services_title': 'Our Services in China',
    'home.china.services_subtitle': 'From our office in Foshan, we support you in all your projects in China',
    'home.china.foshan': 'Foshan, Guangdong',
    'home.china.operations_center': 'Our operations center in China',
    'home.china.expertise_title': 'Services and expertise in China',
    'home.china.expertise_description': 'Our presence in China allows us to offer you comprehensive support for all your business and personal projects.',
    'home.china.services.sourcing': 'Sourcing and Purchasing',
    'home.china.services.sourcing_desc': 'Assistance to find the best suppliers and negotiate prices',
    'home.china.services.currency': 'Currency Exchange',
    'home.china.services.currency_desc': 'Conversion between Yuan, FCFA and Dollars at competitive rates',
    'home.china.services.quality': 'Quality Control',
    'home.china.services.quality_desc': 'Inspection of products before shipment to ensure their quality',
    'home.china.services.admin': 'Administrative Assistance',
    'home.china.services.admin_desc': 'Help with visas, immigration and administrative procedures',
    'home.china.discover_all': 'Discover all our services in China',
    
    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Your reliable gateway to international trade',
    'about.history_title': 'Our History',
    'about.mission_title': 'Our Mission',
    'about.vision_title': 'Our Vision',
    'about.team_title': 'Our Team',
    
    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive solutions for your business needs',
    'services.all': 'All services',
    'services.cargo_china_africa_title': 'Air & Sea Freight China-Africa',
    'services.cargo_china_africa_desc': 'Cargo transportation between China and Africa',
    'services.cargo_china_usa_title': 'Air & Sea Freight China-Canada & USA',
    'services.cargo_china_usa_desc': 'Cargo transportation between China and North America',
    'services.currency_title': 'Currency Exchange',
    'services.currency_desc': 'Currency conversion between Yuan, FCFA, and Dollars',
    'services.china_consulting_title': 'Consulting and Assistance for Purchases in China',
    'services.china_consulting_desc': 'Support for your purchases and negotiations in China',
    'services.travel_title': 'Travel-Tourism-Training',
    'services.travel_desc': 'Travel organization, training, and tourism',
    'services.free_consultation': 'Free Consultation',
    'services.need_custom_service': 'Need a Custom Service?',
    'services.custom_service_desc': 'We offer tailored solutions to meet your specific needs.',
    'services.sea_transport': 'Sea Transport',
    'services.sea_transport_desc': 'Maritime transportation of goods with real-time tracking and complete documentation.',
    'services.air_transport': 'Air Transport',
    'services.air_transport_desc': 'Fast delivery via air freight for your urgent or high-value goods.',
    'services.door_to_door': 'Door-to-Door Services',
    'services.door_to_door_desc': 'Complete transportation from the factory to your warehouse or point of sale.',
    'services.real_time_tracking': 'Real-Time Tracking',
    'services.real_time_tracking_desc': 'Access to our tracking platform to know the exact position of your goods.',
    'services.why_choose_cargo': 'Why choose our freight services?',
    'services.reliability': 'Guaranteed reliability',
    'services.reliability_desc': 'More than 95% of our deliveries arrive on schedule',
    'services.competitive_rates': 'Competitive rates',
    'services.competitive_rates_desc': 'Optimized prices thanks to our partnerships with major companies',
    'services.personalized_service': 'Personalized service',
    'services.personalized_service_desc': 'Each client benefits from a dedicated advisor to follow their shipments',
    'services.global_network': 'Global network',
    'services.global_network_desc': 'Partners in more than 50 countries for optimal coverage',
    'services.request_quote': 'Request a quote',
    'services.global_solutions': 'Global solutions tailored to your international needs',
    'services.global_presence': 'With offices in Cameroon and China, Paul World Travel offers you a complete range of services to facilitate your business and personal projects between Africa, Asia, and North America.',
    'services.personalized_service': 'Personalized service',
    'services.personalized_service_desc': 'Each client benefits from a dedicated advisor to track their shipments',
    'services.global_network': 'Global network',
    'services.global_network_desc': 'Partners in more than 50 countries for optimal coverage',
    'services.request_quote': 'Request a quote',
    'services.global_solutions': 'Global solutions tailored to your international needs',
    'services.global_presence': 'With offices in Cameroon and China, Paul World Travel offers a full range of services to facilitate your commercial and personal projects between Africa, Asia, and North America.',
    'services.estimate_price': 'Estimate a price',
    'services.business_travel': 'Business Travel',
    'services.business_travel_desc': 'Organized travel and customized training programs',
    'services.translation_title': 'Translation Services',
    'services.translation_desc': 'Professional translation services for documents and meetings',
    'services.training_title': 'Training Programs',
    'services.training_desc': 'Customized training programs to suit your needs',
    'services.plan_trip': 'Plan Your Trip',
    'services.need_custom_service': 'Need a Custom Service?',
    'services.custom_service_desc': 'We offer tailored solutions to meet your unique needs.',
    'services.visa_subtitle': 'Visa Assistance and Processing',
    'services.student_visa': 'Student Visa',
    'services.student_visa_desc': 'Comprehensive support for student visa applications.',
    'services.student_visa_support': 'Application Support',
    'services.student_visa_counseling': 'Counseling and Guidance',
    'services.student_visa_interview': 'Interview Preparation',
    'services.student_visa_follow_up': 'Follow-up Services',
    'services.permanent_residence': 'Permanent Residence',
    'services.permanent_residence_desc': 'Assistance with permanent residence applications.',
    'services.permanent_residence_support': 'Application Support',
    'services.permanent_residence_eligibility': 'Eligibility Assessment',
    'services.permanent_residence_preparation': 'Document Preparation',
    'services.permanent_residence_follow_up': 'Follow-up Services',
    'services.other_immigration_services': 'Other Immigration Services',
    'services.business_visa': 'Business Visa',
    'services.business_visa_desc': 'Support for business visa applications and renewals.',
    'services.work_visa': 'Work Visa',
    'services.work_visa_desc': 'Comprehensive assistance for work visa applications.',
    'services.family_reunification': 'Family Reunification',
    'services.family_reunification_desc': 'Guidance on family reunification processes.',
    'services.refugee_status': 'Refugee Status',
    'services.refugee_status_desc': 'Assistance with refugee status applications and support.',
    'services.free_consultation': 'Free Consultation',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are at your disposal to answer all your questions',
    'contact.send_message': 'Send us a message',
    'contact.send_button': 'Send message',
    'contact.first_name': 'First Name',
    'contact.last_name': 'Last Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.select_subject': 'Select a subject',
    'contact.cargo_services': 'Cargo services',
    'contact.currency_exchange': 'Currency exchange',
    'contact.consulting': 'Consulting and assistance',
    'contact.visa': 'Visa services',
    'contact.business': 'Business creation',
    'contact.it': 'IT solutions',
    'contact.customs': 'Customs and transit',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.sending': 'Sending...',
    'contact.send': 'Send message',
    'contact.success': 'Your message has been sent successfully. We will contact you soon.',
    'contact.error': 'An error occurred while sending your message. Please try again.',
    'contact.our_coordinates': 'Our contact information',
    'contact.china_office': 'China Office',
    'contact.china_address': 'Foshan, Guangdong, China',
    'contact.contact_for_info': 'Contact us for more information',
    'contact.cameroon_office': 'Cameroon Office',
    'contact.cameroon_address': 'Douala, Lendi Commissioner Entrance',
    'contact.business_hours': 'Business Hours',
    'contact.monday_friday': 'Monday - Friday: 8:00 AM - 5:00 PM',
    'contact.saturday': 'Saturday: 9:00 AM - 1:00 PM',
    'contact.sunday': 'Sunday: Closed',
    'contact.email_address': 'paulworld2016@yahoo.com',
    'contact.form_name': 'Name',
    'contact.form_phone': 'Phone',
    'contact.form_subject': 'Subject',
    'contact.form_message': 'Message',
    'contact.form_submit': 'Send',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.office_hours': 'Office Hours',
    
    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'Discover our comprehensive range of international services',
    'services.cargo': {
      'title': 'Cargo Services',
      'subtitle': 'Transport solutions between China, Africa, and North America',
      'desc': 'Sea and air freight services connecting China with Africa and North America'
    },
    'services.currency_title': 'Currency Exchange',
    'services.currency_desc': 'Competitive rates for Yuan, CFA, and Dollar conversions',
    'services.consulting_title': 'Consulting & Assistance',
    'services.consulting_desc': 'Expert guidance for your China-related projects',
    'services.travel_title': 'Travel & Tourism',
    'services.travel_desc': 'Organized travel packages and business trips',
    'services.training_title': 'Professional Training',
    'services.training_desc': 'Custom training programs for your team',
    'services.visa_title': 'Visa Services',
    'services.visa_desc': 'Assistance with all types of visa applications',
    'services.door_to_door_desc': 'Complete transportation from the factory to your warehouse or point of sale.',
    'services.real_time_tracking': 'Real-Time Tracking',
    'services.real_time_tracking_desc': 'Access to our tracking platform to know the exact position of your goods.',
    'services.why_choose_cargo': 'Why choose our freight services?',
    'services.why_choose_cargo_desc': 'Years of experience, reliable partners, and exceptional customer service',
    'services.reliability': 'Guaranteed Reliability',
    'services.reliability_desc': 'Reliable partners and constant tracking of your goods',
    'services.tracking': 'Real-Time Tracking',
    'services.tracking_desc': '24/7 access to the exact position of your goods',
    'services.customer_service': 'Exceptional Customer Service',
    'services.customer_service_desc': 'Dedicated team to meet your needs',
    'services.experience': 'International Experience',
    'services.experience_desc': 'Years of experience in international freight',
    'services.global_network': 'Global Network',
    'services.global_network_desc': 'Reliable partners worldwide',
    'services.logistics_expertise': 'Logistics Expertise',
    'services.logistics_expertise_desc': 'Team of experts to optimize your deliveries',
    'services.quality_control': 'Quality Control',
    'services.quality_control_desc': 'Inspection of your goods before shipment',
    'services.custom_solutions': 'Custom Solutions',
    'services.custom_solutions_desc': 'Solutions tailored to your specific needs',
    'services.why_choose_us': 'Why Choose Us?',
    'services.why_choose_us_desc': 'Years of experience, reliable partners, and exceptional customer service',
    
    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Answers to your questions about Paul World Travel',
    'faq.search_placeholder': 'Search for a question...',
    'faq.category_all': 'All Questions',
    'faq.category_cargo': 'Air and Sea Cargo',
    'faq.category_currency': 'Currency Exchange',
    'faq.category_visa': 'Visas and Immigration',
    'faq.category_consulting': 'Consulting and Purchasing',
    'faq.category_it': 'IT Solutions',
    'faq.category_customs': 'Customs and Transit',
    'faq.no_questions': 'No questions found in this category.',
    'faq.more_questions': 'Do you have more questions?',
    'faq.contact_description': 'Our team is available to answer all your specific questions and provide you with the information you need.',
    
    // Locations Page
    'locations.title': 'Our Locations',
    'locations.subtitle': 'Present in China and Cameroon to serve you',
    'locations.china_office': 'Our Office in China',
    'locations.china_office_alt': 'Office in China',
    'locations.china_description': 'Our main office is located in Foshan, in Guangdong province, China, a strategic region that is one of the most important manufacturing centers in the country. This location allows us to work directly with many suppliers and manufacturers to offer you the best services and products.',
    'locations.china_address': 'Foshan, Guangdong, China',
    'locations.contact_for_info': 'Contact us for more information',
    'locations.cameroon_office': 'Our Office in Cameroon',
    'locations.cameroon_office_alt': 'Office in Cameroon',
    'locations.cameroon_description': 'Our office in Cameroon is located in Douala, the economic capital of the country. This presence in Africa allows us to facilitate trade between China and Africa, and to offer a local service to our African clients. Our local team accompanies you in all your projects with expertise and professionalism.',
    'locations.cameroon_address': 'Douala, Lendi Entrée Commisssaire, Cameroun',
    'locations.global_presence': 'Our International Presence',
    'locations.global_description': 'Paul World Travel is strategically positioned to facilitate exchanges between Asia, Africa, and North America. Our presence in China and Cameroon allows us to offer a personalized and efficient service to our international clients.',
    'locations.map_alt': 'World map showing our locations',
    'locations.address': 'Address',
    'locations.hours': 'Office Hours',
    'locations.douala_address': 'Douala, Lendi Entrée Commisssaire',
    
    // Testimonials
    'testimonials.title': 'Customer Testimonials',
    'testimonials.subtitle': 'What our customers say about us',
    'testimonials.add_button': 'Add a testimonial',
    'testimonials.form_name': 'Your Name',
    'testimonials.form_company': 'Company (optional)',
    'testimonials.form_rating': 'Rating',
    'testimonials.form_message': 'Your testimonial',
    'testimonials.form_submit': 'Submit',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success!',
    'common.read_more': 'Read more',
    'common.learn_more': 'Learn more',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.next': 'Next'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Utilisez fr comme langue par défaut
  const [language, setLanguage] = useState<Language>('fr');

  // Fonction de traduction
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personnalisé pour utiliser le contexte de langue
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
